apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: dev
spec:
  maxReplicas: 2  # Cluster Autoscaling 을 확인하기 위하여 일부러 낮게 설정함
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: web-deploy
  targetCPUUtilizationPercentage: 20  # Cluster Autoscaling 을 확인하기 위하여 일부러 낮게 설정함