apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: developer-role
rules:
  - apiGroups: ["", apps", "extensions"]
    resources: ["deployments", "services", "configmaps", "pods"]
    verbs: ["get", "describe", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: dev
roleRef:
  kind: Role 
  name: developer-role 
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: developer
    apiGroup: rbac.authorization.k8s.io